
ALTER TABLE products DROP CONSTRAINT products_type_check;
ALTER TABLE products ADD CONSTRAINT products_type_check CHECK (type = ANY (ARRAY['JUEGOS_PARRILLEROS', 'CUCHILLOS_CHICOS', 'CUCHILLOS_MEDIANOS', 'CUCHILLOS_ESPECIALES', 'CUCHILLOS_RAROS', 'FACONES_Y_DAGAS', 'GAMA_PREMIUM', 'ACCESORIOS']));
